apiVersion: v1
items:
- apiVersion: v1
  data:
    password: TGE2c2Y2RWcxbzFwWmw3ZA==
  kind: Secret
  metadata:
    creationTimestamp: "2025-10-14T19:51:35Z"
    name: argocd-initial-admin-secret
    namespace: argocd
    resourceVersion: "83165"
    uid: 5e48cf7f-1d9b-4186-bc57-8b8635d92819
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"notifications-controller","app.kubernetes.io/name":"argocd-notifications-controller","app.kubernetes.io/part-of":"argocd"},"name":"argocd-notifications-secret","namespace":"argocd"},"type":"Opaque"}
    creationTimestamp: "2025-10-14T19:29:15Z"
    labels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/part-of: argocd
    name: argocd-notifications-secret
    namespace: argocd
    resourceVersion: "80901"
    uid: 58e5895a-3180-4eab-910e-f80b727146b7
  type: Opaque
- apiVersion: v1
  data:
    auth: VjRLdzFQa2R4RUtlbnB4TA==
  kind: Secret
  metadata:
    creationTimestamp: "2025-10-14T19:44:50Z"
    name: argocd-redis
    namespace: argocd
    resourceVersion: "82347"
    uid: 6879fca7-2c38-4c5b-9581-73fd69f297e9
  type: Opaque
- apiVersion: v1
  data:
    admin.password: JDJhJDEwJDhNaG96NGVBYW03dWhmdXd1Zm0vTXV1aVpjUzcvYVBtOThKZGhoRndrRG4yUGI5d1Bkd0Zt
    admin.passwordMtime: MjAyNS0xMC0xNFQxOTo1MTozMVo=
    server.secretkey: VDluSVEzNmZ6NEpXd2c4ZkRjbmYvVmRGZXJIVkFIeTBiQXFMQ2lpMWJZZz0=
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZakNDQWtxZ0F3SUJBZ0lRWjVBQTlOWFNwY2FRVHJpYVpVLzYwREFOQmdrcWhraUc5dzBCQVFzRkFEQVMKTVJBd0RnWURWUVFLRXdkQmNtZHZJRU5FTUI0WERUSTFNVEF4TkRFNU5URTBOVm9YRFRJMk1UQXhOREU1TlRFMApOVm93RWpFUU1BNEdBMVVFQ2hNSFFYSm5ieUJEUkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU00L3hpdWJwcFhBRHIwekNUZXZmWUY2aWppN3BMVnV3aDI0OENkbWtPaGtHVk11L1VwSThyaDAKTExRczV4L2cwTG5SL0NKaGQyREphM3hXT2ZPd01xdEMzeUNhRjVxRjgxWFQ1ZzV3NW4rOW5KdDV6NTNLdGhDKwpCSGFWZTNYeFJ2WmRoRExLS1N5WDh0OXFMWWhNdzB4K1dRN0ZNMmhuRW5QTUtGUi9DMnp1ZWcrYTMwRld2NXR6CjZxSFJ3ZmxQdmlpUFh5QVJ4b3A1dlJtcmVpZW5yUE1GRlo2UjQxUTQxRFNONXNzNE9wZTZKeVlTVEsxd2QvV0EKRDhPaCt2bnByU09FUjRqb2kxMWhOeEZZbktYT0R5OVZndnFLNE5DTDkzMmREMHBWRUEybGdEQ05QZjU1ZDZ2NgpXRHpwRWxwdDlIZHZaWmZsRUMxUjh2Y1FqdncyQ0lNQ0F3RUFBYU9Cc3pDQnNEQU9CZ05WSFE4QkFmOEVCQU1DCkJhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQjdCZ05WSFJFRWREQnkKZ2dsc2IyTmhiR2h2YzNTQ0RXRnlaMjlqWkMxelpYSjJaWEtDRkdGeVoyOWpaQzF6WlhKMlpYSXVZWEpuYjJOawpnaGhoY21kdlkyUXRjMlZ5ZG1WeUxtRnlaMjlqWkM1emRtT0NKbUZ5WjI5alpDMXpaWEoyWlhJdVlYSm5iMk5rCkxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkovZlBJd3ZDdmJITXMKMXRvOXMxeDBsNWFXUUFQeGMyQTlzcnBhMGNncGZnV2dtbnBTVm1jbTRyUEE3S2xMcjVJeTd4MFIycUhBOVRqZQpvTUZDNjFFUlVhcGJtZEI1Wk1vcHVoWEpXNis5QUVEODZLVmo0Q3VnbkFLREx1aDV0UlBuMnczQ3BpdXBTUGc3Ck1YaVN6Y3VsTGxpYUs0MEZ1OFczTmo2dUlEN1IzaWRlWVBSWGk4U3FMZWNRMHdXVEo1NWk5NGJUMnBMZ091YlEKVGpIaTFiWnJ4MVM4cFhUbTVSc1d5WTIwanFKbU9vWEpkdktsTUlqMUVFcHkwR1dEMTZSdkJyNU1WUldQbDdpKwppSW8xTHdETGkzc3U0c2JQKzYwTjIwdUFiSGNIdEIwWE1lbHBITi83NnNqTTIvL3FFM05yT1JNMUk4R2prZTZaCktmcTJmcjJ6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBemovR0s1dW1sY0FPdlRNSk42OTlnWHFLT0x1a3RXN0NIYmp3SjJhUTZHUVpVeTc5ClNranl1SFFzdEN6bkgrRFF1ZEg4SW1GM1lNbHJmRlk1ODdBeXEwTGZJSm9YbW9YelZkUG1EbkRtZjcyY20zblAKbmNxMkVMNEVkcFY3ZGZGRzlsMkVNc29wTEpmeTMyb3RpRXpEVEg1WkRzVXphR2NTYzh3b1ZIOExiTzU2RDVyZgpRVmEvbTNQcW9kSEIrVSsrS0k5ZklCSEdpbm05R2F0Nko2ZXM4d1VWbnBIalZEalVOSTNteXpnNmw3b25KaEpNCnJYQjM5WUFQdzZINitlbXRJNFJIaU9pTFhXRTNFVmljcGM0UEwxV0Mrb3JnMEl2M2ZaMFBTbFVRRGFXQU1JMDkKL25sM3EvcFlQT2tTV20zMGQyOWxsK1VRTFZIeTl4Q08vRFlJZ3dJREFRQUJBb0lCQUJzNDI2VWgxQ2pyd29aQwpXRE1iWEl0Y2F5WDF6bFdNR3Q3bGEvMG5VblQ1MFVYamE5Y0VMZFVlc0UvUHBXblZ1SGJ1T2tNbmJpUStNWXVsCnJkeDJJeG5ycDV1Yit3V1FMSC9saWZYWi9QSmJTbkpTNzQ0NkZURzhnc1pNRUpHT21Qa25lcTFoZFhISFZHMGMKaklueTU4d08yUjVUOU9jUXc2UzVDNUdyZXd5VGFLbVdlWWdwd21nYWRMK0REWmxtd0swWnExNnJjYWkvZURTegppZVZwT0pjKy84Z0hRSlo5cWhOZmFjeWMzOHFzOEI4R0VCVnFLb2xEaXZDVWliQnNxZDhFalhCMWpGNWNxWFR3CjFGWGxiUm01TmZSNytaczFxcnNqcE1yM0kxS2dkUVREbzd0akp4VVZCMytsaThqdWFreE4vVHZRcXJrN3ZyYm4KZTNPWm13RUNnWUVBNFQ0a21WZ0syTFo3MFI3VDJoTFIyeEFCZVJZRDI1NnFKcnZZeWZnWi82U3RtSGkvcktragpOclFVTkp4K1ZnK0JzdWduRjRwWTRiQTRaZDVMb0RLV0kzMWdIcFBlVk1PVkwyZU9oaFF6c0k0VGlUQ05oZVFCClR6UFNiVitvdXdYbFQrRGF1UVY0MGhWc2RodERmL2xPRkk2WElmUTMzdXZWZlppTWRLa2V3VU1DZ1lFQTZtbXEKdmYyUGlrUFRqY05sc1l5L2h2L2NqSmVPTEo0QU5zUzBQeHB5emVnRFdUQkVidmRmdEk0NUJta0NWSWpLZEQ0MQprOXVWRXFXekI1ZFc0UnozQTRnOHhSS0wvbjJYZVZJODRXVGNva0E4SUJndXh0cFZGMnl6OXVXR2oxY1NwdVM0ClhWZjZQWVlZak5GTFEzYklTNDVrajFtaHdLMk4rd0N4WDR1MGg4RUNnWUVBMWlibFdUNVNJYlZ1aDJjTitWckgKVjhZaUFHUWtDdDBSM1gzZ0lqYlhVUzNiTndvbkF4eFV0S0FHVGZjMFR0S3pkOHd0enIza3Y3OXgvN2lZb3BrMgpFa3dUNVQ2bHRtVzJJN29MMGdMSEdtZ2F2dWNBeDNuK25MVWlyb2F5d0E1YzlkTk5ZWGlJWlFXbGQ2MTRRZVpnCmpENytCblJSNG9yTEVuekZuZTFscGswQ2dZQU45T2lqa3pzK29qY3dVNWYwY0VyZkFORGkxZ3N6QU4xR1pZUE4KMWdkTDF5cUwzdUhVTVlwVE43eVJjeU1lWVY2Y2VTKzdjL0YyUU1OZUNsYXo1SU9ZaEQ0S0JjYXNDbEpBZVBNRApBSHhhZExTZnZKRGNhaGR5NDVmN2RVTUR1YzEwZmwyendRODNKb3JEcDVweGs5cnRGTGRNQ2F3bHlxK1BhRVVuClNTd2dnUUtCZ0NJMURQYzZvU0tvcVkyQm9vNjZ4ckhGWGRIdmd0RW9DSEVTeW9EUzBLT3pUY0M0MmJINmJnb2EKSmlGSHFiMGZ4d1Z3aEg4SkdVR3FNaWdONmdGZXV2bkpGU3pjMldrdkhJOHhKcUxBSTIyQ25Lc3VjelZVb3BRTQpFVVErS0F4YkxLWGYvRDdvRVRLa2dwZHFGVG1qODBxd05zYjhHV2MyRW84SFlacXpwVjExCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-secret","app.kubernetes.io/part-of":"argocd"},"name":"argocd-secret","namespace":"argocd"},"type":"Opaque"}
    creationTimestamp: "2025-10-14T19:29:16Z"
    labels:
      app.kubernetes.io/name: argocd-secret
      app.kubernetes.io/part-of: argocd
    name: argocd-secret
    namespace: argocd
    resourceVersion: "83184"
    uid: 81c057b9-8ee2-4d8d-b67f-813cff487c52
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
